"""survey_block

Revision ID: d19d802df5eb
Revises: 9a01d128cc52
Create Date: 2022-12-20 16:52:04.315006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd19d802df5eb'
down_revision = '9a01d128cc52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagement_status_block',
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=True),
    sa.Column('survey_status', sa.Enum('Upcoming', 'Open', 'Closed', name='submissionstatus'), nullable=False),
    sa.Column('block_text', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('modified_by_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('feedback', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('engagement_status_block')
    # ### end Alembic commands ###
