"""added name for widgets

Revision ID: e5fceb8c33c6
Revises: 46490dc02be5
Create Date: 2022-12-12 10:37:27.482498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5fceb8c33c6'
down_revision = '46490dc02be5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('name', sa.Text(), nullable=True))
    op.drop_index('ix_user_username', table_name='met_users')
    op.create_index(op.f('ix_met_users_username'), 'met_users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_met_users_username'), table_name='met_users')
    op.create_index('ix_user_username', 'met_users', ['username'], unique=False)
    op.drop_column('feedback', 'name')
    # ### end Alembic commands ###
